# Generated by Django 5.2 on 2025-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nmi', models.CharField(max_length=10, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'meter_readings',
                'unique_together': {('nmi', 'timestamp')},
            },
        ),
    ]
