# Generated by Django 5.2 on 2025-05-03 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
