# Generated by Django 5.2 on 2025-05-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion_app', '0002_alter_meterreadings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadings',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
