# Generated by Django 5.2 on 2025-05-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion_app', '0003_alter_meterreadings_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadings',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
